@ecommer_HostAddress = http://127.0.0.1:8000/api


# Register User
POST {{ecommer_HostAddress}}/user
Content-Type: application/json

{
    "email": "gravity125@gmail.com",
    "password": "Password@123",
    "confirm_password": "Password@123"
}
###

# Login User
POST {{ecommer_HostAddress}}/token/
Content-Type: application/json

{
    "email": "gravity125@gmail.com",
    "password": "Password@123",
    "confirm_password": "Password@123"
}
###

# Get Current User
GET {{{{ecommer_HostAddress}}}}/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMjMwNDQ0LCJpYXQiOjE3NjEyMjkyNDQsImp0aSI6ImQ0ZDRkODY5ODk5YjQ5NWViNTRlZDUxNDMwYjJkYjJjIiwidXNlcl9pZCI6IjU3NzVjMDlkLTkxN2QtNDBiZS1iNzAxLTExZDg4YTk0MDEzYyJ9.HIWl4WWB69pc3cqJmEaMdbBFQZZe0Mxfix8VoxlrAU4

###

# Access Vendor-Only Endpoint
GET {{ecommer_HostAddress}}/vendor-only
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMjMwNDQ0LCJpYXQiOjE3NjEyMjkyNDQsImp0aSI6ImQ0ZDRkODY5ODk5YjQ5NWViNTRlZDUxNDMwYjJkYjJjIiwidXNlcl9pZCI6IjU3NzVjMDlkLTkxN2QtNDBiZS1iNzAxLTExZDg4YTk0MDEzYyJ9.HIWl4WWB69pc3cqJmEaMdbBFQZZe0Mxfix8VoxlrAU4

###

# List All Products
GET {{ecommer_HostAddress}}/products/all
Content-Type: application/json

###